<?php

namespace app\admin\controller\finance;

use app\common\controller\Backend;
use think\Cache;
use think\Controller;
use think\Db;
use think\Request;

class RealTimeStock extends Backend
{
    public function _initialize()
    {
        $this->model = new \app\admin\model\itemmanage\Item;
        return parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        //设置过滤方法
        $this->request->filter(['strip_tags']);
        if ($this->request->isAjax()) {
            //如果发送的来源是Selectpage，则转发到Selectpage
            if ($this->request->request('keyField')) {
                return $this->selectpage();
            }
            $filter = json_decode($this->request->get('filter'), true);
            if($filter['sku']){
                $map['sku'] = $filter['sku'];
            }
            $map['is_del'] = 1;
            $map['is_open'] = 1;
            unset($filter['sku']);
            $this->request->get(['filter' => json_encode($filter)]);
            list($where, $sort, $order, $offset, $limit) = $this->buildparams();
            $total = $this->model
                ->where($where)
                ->where($map)
                ->order($sort, $order)
                ->count();
            $list = $this->model
                ->where($where)
                ->where($map)
                ->order($sort, $order)
                ->limit($offset, $limit)
                ->field('id,sku,stock*purchase_price price')
                ->select();
            $list = collection($list)->toArray();
            $result = array("total" => $total, "rows" => $list);
            return json($result);
        }
        //库存总金额
        $flag['is_del'] = 1;
        $flag['is_open'] = 1;
        $stock_total = $this->model->where($flag)->sum('stock*purchase_price');
        $this->view->assign('stock_total',$stock_total);
        return $this->view->fetch();
    }
    public function detail()
    {
        return $this->view->fetch();
    }
}
