<?php
/**
 * @Author: CrashpHb彬
 * @Date: 2020/3/16 9:15
 * @Email: 646054215@qq.com
 */

namespace app\api\controller;


use think\Controller;
use EasyDingTalk\Application;

class Ding extends Controller
{
    protected $app = null;
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        try{
            $this->app = new Application(config('ding'));
        }catch (\Exception $e){
            echo $e->getMessage();
        }
    }
    public function test()
    {
        $attendance = $this->app->attendance->groups();
        dump($attendance);
    }
}